version: '3.8'
services:
  dohproxy:
    build: .
    container_name: dohproxy
    ports:
      - "5353:5353/udp"
      - "5353:5353/tcp"
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./config.yaml:/app/config.yaml:ro
