version: '3.8'
services:
  dohproxy:
    build: .
    container_name: dohproxy
    ports:
      - "5300:5300/udp"
      - "5300:5300/tcp"
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./config.yaml:/app/config.yaml:ro
